In [1]:
import numpy as np

In [6]:
arr = np.array([1, 4, 7])                     #Array from list

In [7]:
arr                                           #1D - Array

array([1, 4, 7])

In [10]:
arr2 = np.array([[1, 4, 7], [4, 6 , 8]])                 #2D - Array
arr2

array([[1, 4, 7],
       [4, 6, 8]])

## Creating array from scratch

In [12]:
np.zeros((3, 4))                               #3 Columns and 4 Rows 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))                                #Same for fill with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.full((4,6), 6)                             #First bracet define size and 2nd with whoome fill

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [20]:
np.eye(5)                                    #Identity Matrics

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(1, 10, 3)                        #Gives values from 1 to 10 by adding +3

array([1, 4, 7])

In [25]:
np.linspace(1, 100, 5)                    #Equally spaced array of 5 ele Between 1 to 100

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [29]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [31]:
myarr.shape              

(4, 3)

In [32]:
myarr.size

12

In [36]:
myarr.ndim             #Define dimensions of array

2

In [37]:
myarr.dtype

dtype('int64')

### Changing Data Types

In [38]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype = 'float32')

In [39]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [41]:
n = myarr.astype('float64')                #Converting existing array
n.dtype

dtype('float64')

### Reshaping Array

In [42]:
myarr.shape

(4, 3)

In [43]:
reshaped = myarr.reshape(3,4)
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [45]:
reshaped2 = myarr.reshape(2,6)                       #It only reshape in same ele
reshaped2                                            #Like we have 3*4 array so we can conver 4*3=12   2*6=12

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)

In [49]:
myarr.flatten()                                    #Convert any array to 1D array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)