In [1]:
import numpy as np

In [3]:
arr = np.random.rand(3,3)
arr

array([[0.15436529, 0.61992211, 0.07102054],
       [0.93738796, 0.3039277 , 0.56719361],
       [0.19036952, 0.37336741, 0.57845105]])

In [4]:
arr.shape

(3, 3)

In [7]:
arri = arr.astype('int32')
arri.dtype

dtype('int32')

In [8]:
arr3 = np.arange(1, 16)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr3[[1, 3, 5, 7, 9]]

array([ 2,  4,  6,  8, 10])

In [10]:
arr4 = np.arange(1, 10)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr5 = np.arange(20,70)
arr5


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [14]:
arr5[arr5>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])