# 🧩 Indexing and Slicing in NumPy

NumPy arrays allow you to access and manipulate elements efficiently.  
Let’s explore **indexing** and **slicing**, which are fundamental for working with arrays.

---

## 🔹 Indexing (Same as Python Lists)

```python
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])   # 10 (first element)
print(arr[-1])  # 40 (last element)
```

You can use **positive** or **negative** indices to access elements in a NumPy array.

---

## 🔹 Slicing (Extracting Parts of an Array)

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # [20 30 40] → slice from index 1 to 3
print(arr[:3])    # [10 20 30] → first 3 elements
print(arr[::2])   # [10 30 50] → every 2nd element
```

🧠 **Note:**  
Slicing in NumPy returns a **view**, not a copy.  
This means both arrays share the **same memory** — changes in one affect the other.

---

## ⚙️ Example: Slicing Returns a View

```python
arr = np.array([10, 20, 30, 40, 50])

sliced = arr[1:4]
sliced[0] = 999

print(arr)
# Output: [10 999 30 40 50]
```

As you can see, changing `sliced` also changed the original array!

---

## 🧠 Why Does This Happen?

- **Memory Efficiency:** Avoids unnecessary copies, saving memory.  
- **Performance:** Faster access and manipulation of large datasets.

---

## 🛠️ Creating a Copy (Independent Array)

If you want a **separate copy** of the data that won’t affect the original array:

```python
arr = np.array([10, 20, 30, 40, 50])
copy_arr = arr[1:4].copy()

copy_arr[0] = 999
print(arr)       # [10 20 30 40 50] (unchanged)
print(copy_arr)  # [999 30 40]
```

✅ Use `.copy()` whenever you want an **independent** array.

---

**Summary:**
- Indexing gives individual elements.
- Slicing extracts parts of an array.
- NumPy slicing returns **views** (shared memory).
- Use `.copy()` to make **independent copies**.


In [1]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]                                 #Same as py list slicing

np.int64(1)

In [8]:
flat[3:8]

array([4, 5, 6, 7, 8])

In [9]:
flat[::2]                             #It gives every 2nd ele

array([ 1,  3,  5,  7,  9, 11])

### Slicing returns view not a copy
- NumPy returns data from og soruce
- View means changes made reflects in og array

In [11]:
b = flat[:5]
b

array([1, 2, 3, 4, 5])

In [14]:
b[0] = 4444
b                                       #Returns from og array not a copy

array([4444,    2,    3,    4,    5])

In [15]:
flat                                    #Changes made in og flat array

array([4444,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12])

### Fancy Indexing & Boolean Masking

In [17]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [21]:
arr[[0, 2, 4]]                       #Multi Indexing 

array([10, 30, 50])

In [22]:
arr2 = np.array([10, 20, 30, 40, 50])
arr2

array([10, 20, 30, 40, 50])

In [24]:
arr2[arr2>20]                   #Boolean masking = Putting Condition 

array([30, 40, 50])