# 🧠 Multidimensional Indexing and Axis in NumPy

NumPy allows efficient manipulation of **multidimensional arrays**, where **indexing** and **axis operations** are essential concepts — especially in **data science** and **machine learning**.

---

## 1️⃣ Understanding Axes in NumPy

Each **dimension** in a NumPy array is called an **axis**, numbered from **0**.

| Array Type | Axes Count | Example Meaning |
|-------------|-------------|----------------|
| 1D array | 1 axis | `axis 0` → elements |
| 2D array | 2 axes | `axis 0 = rows`, `axis 1 = columns` |
| 3D array | 3 axes | `axis 0 = depth`, `axis 1 = rows`, `axis 2 = columns` |

### Example: Axes in a 2D Array

```python
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)
```

**Output:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

- **Axis 0 (rows)** → Operations move **down the columns**  
- **Axis 1 (columns)** → Operations move **across the rows**

```python
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)
```

**Output:**
```
[12 15 18]  # Column-wise sum
[ 6 15 24]  # Row-wise sum
```

---

## 2️⃣ Indexing in Multidimensional Arrays

You can access elements using **row and column indices**:

```python
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6
```

You can also use **slicing** to extract parts of an array:

```python
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns
```

**Output:**
```
[[2 3]
 [5 6]]
```

---

## 3️⃣ Indexing in 3D Arrays

For **3D arrays**, the first index refers to the **depth** (like sheets of data).

```python
arr3D = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(arr3D.shape)  # (depth, rows, columns)
```

**Output:**
```
(2, 2, 3)
```

Accessing elements:
```python
print(arr3D[0, 1, 2])  # First sheet, second row, third column → 6
print(arr3D[:, 0, :])  # Get the first row from both sheets
```

---

## 4️⃣ Practical Examples — Selecting Data Along Axes

```python
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)
```

**Output:**
```
[[1 2 3]
 [7 8 9]]
```

---

## 5️⃣ Changing Data Along an Axis

```python
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)
```

**Output:**
```
[[1 0 3]
 [4 0 6]
 [7 0 9]]
```

---

## ✅ Summary

- **Axis 0** → rows (vertical movement)  
- **Axis 1** → columns (horizontal movement)  
- **Indexing** works as:  
  - `arr[row, column]` for 2D arrays  
  - `arr[depth, row, column]` for 3D arrays  
- **Slicing** → extract subarrays efficiently  
- **Axis operations** allow fast computation without explicit loops  

---
💡 *Mastering axes and indexing in NumPy is crucial for effective data wrangling and vectorized computation!*


In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1[0]

array([1, 2, 3])

In [5]:
np.sum(arr1, axis=0)          #0 = Sum of columns 1+4+7     2+5+8

array([12, 15, 18])

In [6]:
np.sum(arr1, axis=1)          #1 = Sum of rows so  here 1+2+3     4+5+6

array([ 6, 15, 24])

### Indexing

In [13]:
arr1[1][1]                   #Basic Indexing

np.int64(5)

In [10]:
arr1[:, 1].sum()             # First is row : means all rows and column only 1

np.int64(15)

In [11]:
arr1[0:2, 1:3]              #All Rows & 1-2 Columns             #0:3 = 0,1,2

array([[2, 3],
       [5, 6]])

### Indexing in 3D Array

In [13]:
 arr3 = np.array([[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]]])

In [14]:
arr3                                 #Here depth 0 = 1st block

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3[1, 0, 1]                   #D=1 means 2nd Array , R=0 , C = 1

np.int64(8)

In [25]:
arr3[0, 1, 1]   

np.int64(5)

In [17]:
arr3[:, 0, 0:2]                  #All Depth, All Columns

array([[1, 2],
       [7, 8]])

### 4. Practical Example: Selecting Data Along Axes

In [31]:
first_row = arr3[0, 0, :]
first_row

array([1, 2, 3])

In [33]:
f_col = arr3[0, :, 0]
f_col

array([1, 4])

### 5. Changing Data Along an Axis

In [34]:
arr3[:, 0, :] = 3
arr3                               #Sleceted index values changed     its like updating data in array

array([[[ 3,  3,  3],
        [ 4,  5,  6]],

       [[ 3,  3,  3],
        [10, 11, 12]]])

### Prac. 

In [18]:
arr4 = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [7, 9, 11]
])
arr4

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 7,  9, 11]])

In [21]:
arr4.sum(axis=1)            # Sum of each Row

array([12,  9, 27])

In [22]:
arr4.sum(axis=0)           # Sum of each column

array([10, 16, 22])

In [24]:
arr4[:, 1:3]               # extract only the 2nd and 3rd columns.

array([[ 4,  6],
       [ 3,  5],
       [ 9, 11]])

In [25]:
arr5 = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])
arr5

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [28]:
# Print the element 70 using indexing.

arr5[1, 1, 0]

np.int64(70)

In [29]:
# Print the first row from both sheets.

arr5[:, 0, :]

array([[10, 20],
       [50, 60]])

In [30]:
# Extract a 2×2 matrix from the first array 

arr4[1:3, 0:2]

array([[1, 3],
       [7, 9]])

In [32]:
# In the first array, replace the first column with all zeros.

arr4[:, 0] = 0         # We have to take all rows and column only 1st
arr4

array([[ 0,  4,  6],
       [ 0,  3,  5],
       [ 0,  9, 11]])

In [38]:
# Create a 3×3 random array and:
# Replace all elements greater than 0.5 with 1
# Replace the rest with 0

arr6 = np.random.rand(3, 3)
arr6

array([[0.77666547, 0.49607662, 0.22463815],
       [0.21498436, 0.78794755, 0.99139542],
       [0.68311433, 0.65941219, 0.90956241]])

In [41]:
arr6 = np.where(arr6 > 0.5, 1, 0)              # We can use np.where to put condtion 
#                 if = 1 , else = 0

In [42]:
arr6

array([[1, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [45]:
arr4 = np.where(arr4 > 5, 0, arr4)        # Where ele is > 5 make it 0     if not do nothing 

In [44]:
arr4

array([[0, 4, 0],
       [0, 3, 5],
       [0, 0, 0]])