In [1]:
import numpy as np

In [6]:
arr1 = np.array([1, 5, 8])

In [7]:
squared = arr1 ** 2 

In [9]:
squared

array([ 1, 25, 64])

In [10]:
arr2 = np.array([[1, 4, 7], [4, 6 , 8]]) 

In [11]:
arr2

array([[1, 4, 7],
       [4, 6, 8]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.linspace(0,2, 2)

array([0., 2.])

In [22]:
arr2.shape

(2, 3)

In [23]:
arr2.size

6

In [24]:
arr2.ndim

2

In [25]:
arr2.dtype

dtype('int64')

In [27]:
arr2.astype('float32')

array([[1., 4., 7.],
       [4., 6., 8.]], dtype=float32)

In [28]:
arr2.dtype

dtype('int64')

In [29]:
arr2.ndim

2

In [32]:
arr2.reshape((3,2))

array([[1, 4],
       [7, 4],
       [6, 8]])

In [33]:
arr2.flatten()

array([1, 4, 7, 4, 6, 8])

In [35]:
arr3 = arr2.flatten()
arr3

array([1, 4, 7, 4, 6, 8])

In [36]:
arr3[0]

np.int64(1)

In [37]:
arr3[0:3]

array([1, 4, 7])

In [42]:
arr3[[0, 2, 1]]

array([1, 7, 4])

In [43]:
arr3[arr3>2]

array([4, 7, 4, 6, 8])

In [47]:
arr5 = np.random.rand(3, 3)

In [48]:
arr6 = arr5.astype('int32')
arr6.dtype

dtype('int32')